export const CURRENT_USER = '/api/current_user'
export const LOGOUT = '/auth/logout'
export const REGISTER = '/auth/register'
export const LOGIN = '/auth/login'
export const ROOMS = '/api/rooms'
export const SINGLE_ROOM = '/api/room'
export const WEBSOCKET_CONNECT = 'http://localhost:5000'
