export const FETCH_USER = 'FETCH_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const FETCH_ROOMS = 'FETCH_ROOMS'
export const ROOM_CHANGE = 'ROOM_CHANGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
